const constants = {
  READ_ALL_POSTS_REQUEST: 'posts/READ_ALL_POSTS_REQUEST',
  READ_ALL_POSTS_SUCCESS: 'posts/READ_ALL_POSTS_SUCCESS',
  READ_ALL_POSTS_FAILURE: 'posts/READ_ALL_POSTS_FAILURE',

  READ_POST_REQUEST: 'posts/READ_POST_REQUEST',
  READ_POST_SUCCESS: 'posts/READ_POST_SUCCESS',
  READ_POST_FAILURE: 'posts/READ_POST_FAILURE',

  DOWNLOAD_POSTS_REQUEST: 'posts/DOWNLOAD_POSTS_REQUEST',
  DOWNLOAD_POSTS_SUCCESS: 'posts/DOWNLOAD_POSTS_SUCCESS',
  DOWNLOAD_POSTS_FAILURE: 'posts/DOWNLOAD_POSTS_FAILURE',

  CLEAR_POSTS_STATE: 'posts/CLEAR_POSTS_STATES',
}

export default constants
